[versions]
junit-jupiter-engine = "5.10.3"
slf4j = "1.7.25"
diagnosekoder = "1.2025.0"

[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
diagnosekoder = { module = "no.nav.helse:diagnosekoder", version.ref = "diagnosekoder" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
