name: Build, test, release
on:
  push:
    paths:
      - .github/workflows/release.yml
      - 'lib/**'

jobs:
  build_and_release:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Test and build lib
        run: ./gradlew build

      - name: Summarize tests results
        uses: navikt/gradle-tests-summary@v1
        if: ${{ always() }}
